import inspect
import json
from typing import Any, Callable, Dict, List, Type
from pydantic import BaseModel

class ToolRegistry:
    """
    A lightweight framework to convert standard Python functions 
    (annotated with Pydantic types) into OpenAI JSON schema representations (tools array).
    """
    def __init__(self):
        self.tools: Dict[str, dict] = {}
        self.functions: Dict[str, Callable] = {}

    def register(self, name: str, description: str, args_schema: Type[BaseModel]):
        """
        Decorator to register a function as an OpenAI tool.
        """
        def decorator(func: Callable):
            self.functions[name] = func
            
            # Generate JSON schema from Pydantic model
            schema = args_schema.model_json_schema()
            
            # Clean up Pydantic-specific fields that OpenAI might not like
            if "$defs" in schema:
                del schema["$defs"]
                
            tool_def = {
                "type": "function",
                "function": {
                    "name": name,
                    "description": description,
                    "parameters": {
                        "type": "object",
                        "properties": schema.get("properties", {}),
                        "required": schema.get("required", []),
                    }
                }
            }
            self.tools[name] = tool_def
            return func
        return decorator

    def get_tools(self) -> List[dict]:
        """Return the list of OpenAI tool definitions."""
        return list(self.tools.values())
        
    async def execute_tool(self, tool_call: dict) -> Any:
        """
        Execute a tool call generated by the LLM.
        """
        name = tool_call.get("name")
        arguments_json = tool_call.get("arguments", "{}")
        
        if name not in self.functions:
            raise ValueError(f"Tool {name} not found in registry.")
            
        try:
            kwargs = json.loads(arguments_json)
        except json.JSONDecodeError:
            kwargs = {}
            
        func = self.functions[name]
        
        # Check if function is async
        if inspect.iscoroutinefunction(func):
            return await func(**kwargs)
        else:
            return func(**kwargs)
