import pptxgen from 'pptxgenjs';

export class PresentationService {
  /**
   * Generates a professionally formatted PowerPoint pitch deck for job seekers
   */
  async generateCareerPitchDeck(candidateName: string, candidateData: any, targetRole: string): Promise<Buffer> {
    const pptx = new pptxgen();
    pptx.layout = 'LAYOUT_16X9';

    // Slide 1: Title Slide (Midnight Executive theme)
    let slide1 = pptx.addSlide();
    slide1.background = { fill: '1B365D' };
    
    slide1.addText(candidateName, {
      x: 1.0, y: 2.2, w: 10.0, h: 1.0,
      fontFace: 'Segoe UI', fontSize: 40, bold: true, color: 'FFFFFF',
      align: 'left'
    });
    
    slide1.addText(`Target Role: ${targetRole}`, {
      x: 1.0, y: 3.2, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 18, color: 'D4AF37',
      align: 'left'
    });
    
    slide1.addText('Career Pitch Deck | Generated by CareerForge AI', {
      x: 1.0, y: 5.2, w: 10.0, h: 0.3,
      fontFace: 'Segoe UI', fontSize: 10, italic: true, color: '94A3B8',
      align: 'left'
    });

    // Slide 2: Executive Summary & Highlights
    let slide2 = pptx.addSlide();
    slide2.background = { fill: 'F8FAFC' };
    
    slide2.addText('Professional Overview', {
      x: 0.6, y: 0.5, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 24, bold: true, color: '1B365D'
    });
    
    // Left Summary Card
    slide2.addText(candidateData.summary || 'Experienced professional with a track record of technical delivery and engineering execution.', {
      x: 0.6, y: 1.4, w: 7.0, h: 4.0,
      fontFace: 'Segoe UI', fontSize: 14, color: '334155',
      align: 'left', valign: 'top', lineSpacing: 24
    });
    
    // Right Stats Column
    slide2.addText('KEY METRICS', {
      x: 8.2, y: 1.4, w: 4.0, h: 0.4,
      fontFace: 'Segoe UI', fontSize: 12, bold: true, color: '64748B'
    });
    
    const years = candidateData.experience_years || candidateData.experienceYears || 'N/A';
    const numSkills = candidateData.skills?.length || 0;
    
    const statsText = `• Years of Experience: ${years}\n• Total Skills Tracked: ${numSkills}\n• Top Core Skills: ${candidateData.skills?.slice(0, 4).join(', ') || 'N/A'}`;
    
    slide2.addText(statsText, {
      x: 8.2, y: 2.0, w: 4.5, h: 3.4,
      fontFace: 'Segoe UI', fontSize: 13, color: '334155',
      align: 'left', valign: 'top', lineSpacing: 22
    });

    // Slide 3: Skills Matrix
    let slide3 = pptx.addSlide();
    slide3.background = { fill: 'F8FAFC' };
    
    slide3.addText('Core Competencies & Skills', {
      x: 0.6, y: 0.5, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 24, bold: true, color: '1B365D'
    });
    
    const skills = candidateData.skills || [];
    const chunk = Math.ceil(skills.length / 3) || 4;
    
    for (let i = 0; i < 3; i++) {
      const start = i * chunk;
      const colSkills = skills.slice(start, start + chunk);
      if (colSkills.length === 0) continue;
      
      const text = colSkills.map((s: string) => `• ${s}`).join('\n');
      slide3.addText(text, {
        x: 0.6 + i * 4.0, y: 1.5, w: 3.5, h: 4.0,
        fontFace: 'Segoe UI', fontSize: 13, color: '334155',
        align: 'left', valign: 'top', lineSpacing: 24
      });
    }

    // Slide 4: Career History / Key Projects
    let slide4 = pptx.addSlide();
    slide4.background = { fill: 'F8FAFC' };
    
    slide4.addText('Professional Experience Highlights', {
      x: 0.6, y: 0.5, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 24, bold: true, color: '1B365D'
    });
    
    const exps = candidateData.experience || [];
    const top2 = exps.slice(0, 2);
    
    if (top2.length > 0) {
      top2.forEach((exp: any, index: number) => {
        const yOffset = 1.4 + index * 2.2;
        const title = `${exp.title || 'Role'} at ${exp.company || 'Company'}`;
        const duration = exp.duration || exp.start_date || 'Present';
        
        slide4.addText(title, {
          x: 0.6, y: yOffset, w: 8.0, h: 0.4,
          fontFace: 'Segoe UI', fontSize: 15, bold: true, color: '1B365D'
        });
        
        slide4.addText(duration, {
          x: 9.0, y: yOffset, w: 3.5, h: 0.4,
          fontFace: 'Segoe UI', fontSize: 12, italic: true, color: '64748B',
          align: 'right'
        });
        
        const bulletPoints = typeof exp.description === 'string'
          ? exp.description.split('\n').slice(0, 2).map((line: string) => line.trim().startsWith('-') || line.trim().startsWith('•') ? line : `• ${line}`).join('\n')
          : '• Successfully executed business projects and aligned metrics.';
          
        slide4.addText(bulletPoints, {
          x: 0.6, y: yOffset + 0.4, w: 12.0, h: 1.5,
          fontFace: 'Segoe UI', fontSize: 12, color: '475569',
          align: 'left', valign: 'top', lineSpacing: 20
        });
      });
    } else {
      slide4.addText('No detailed career history provided.', {
        x: 0.6, y: 1.8, w: 10.0, h: 1.0,
        fontFace: 'Segoe UI', fontSize: 14, color: '64748B'
      });
    }

    // Slide 5: Value Proposition & Contact
    let slide5 = pptx.addSlide();
    slide5.background = { fill: '1B365D' };
    
    slide5.addText('Key Value Proposition', {
      x: 1.0, y: 1.0, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 28, bold: true, color: 'FFFFFF'
    });
    
    const valuePropText = `• Action-oriented professional matching core qualifications of target role.\n• Skilled at bridging technology and core business metrics.\n• Collaborative leader eager to contribute to target team's roadmap.`;
    
    slide5.addText(valuePropText, {
      x: 1.0, y: 1.8, w: 11.0, h: 2.2,
      fontFace: 'Segoe UI', fontSize: 15, color: 'F8FAFC',
      align: 'left', valign: 'top', lineSpacing: 26
    });
    
    const contact = `Contact Information:\nEmail: ${candidateData.contact?.email || 'N/A'} | Phone: ${candidateData.contact?.phone || 'N/A'}`;
    slide5.addText(contact, {
      x: 1.0, y: 4.5, w: 11.0, h: 1.0,
      fontFace: 'Segoe UI', fontSize: 13, italic: true, color: 'D4AF37'
    });

    const buffer = await pptx.write({ outputType: 'arraybuffer' }) as ArrayBuffer;
    return Buffer.from(buffer);
  }

  /**
   * Generates a talent pipeline presentation report for recruiters
   */
  async generateTalentPipelineReport(jobTitle: string, jobSkills: string[], candidates: any[]): Promise<Buffer> {
    const pptx = new pptxgen();
    pptx.layout = 'LAYOUT_16X9';

    // Slide 1: Title (Teal Trust theme)
    let slide1 = pptx.addSlide();
    slide1.background = { fill: '0F766E' };
    
    slide1.addText('Talent Match Report', {
      x: 1.0, y: 2.0, w: 10.0, h: 1.0,
      fontFace: 'Segoe UI', fontSize: 38, bold: true, color: 'FFFFFF'
    });
    
    slide1.addText(`Job Posting: ${jobTitle}`, {
      x: 1.0, y: 3.0, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 18, color: '2DD4BF'
    });
    
    slide1.addText(`Evaluation Cohort: ${candidates.length} candidates | Powered by CareerForge AI`, {
      x: 1.0, y: 5.0, w: 10.0, h: 0.4,
      fontFace: 'Segoe UI', fontSize: 11, color: 'F1F5F9'
    });

    // Slide 2: Candidates Match Table
    let slide2 = pptx.addSlide();
    slide2.background = { fill: 'F1F5F9' };
    
    slide2.addText('Candidate Rankings Summary', {
      x: 0.6, y: 0.4, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 24, bold: true, color: '0F766E'
    });
    
    const tableHeader = [
      { text: 'Rank', options: { bold: true, fill: { color: '0F766E' }, color: 'FFFFFF' } as any },
      { text: 'Candidate Name', options: { bold: true, fill: { color: '0F766E' }, color: 'FFFFFF' } as any },
      { text: 'Match Score', options: { bold: true, fill: { color: '0F766E' }, color: 'FFFFFF' } as any },
      { text: 'Primary Strength / Fit Notes', options: { bold: true, fill: { color: '0F766E' }, color: 'FFFFFF' } as any }
    ];
    
    const tableRows: any[] = [tableHeader];
    const sorted = candidates.sort((a, b) => {
      const scoreA = a.overall_score || a.score || 0;
      const scoreB = b.overall_score || b.score || 0;
      return scoreB - scoreA;
    }).slice(0, 5);
    
    sorted.forEach((cand, index) => {
      const score = cand.overall_score || cand.score || 0;
      const scoreStr = score <= 1.0 ? `${(score * 100).toFixed(0)}%` : `${score}%`;
      const rec = cand.recommendations?.[0] || cand.reasons?.[0] || 'Matches core qualifications.';
      
      tableRows.push([
        { text: (index + 1).toString(), options: {} as any },
        { text: cand.name || `Candidate ${index + 1}`, options: {} as any },
        { text: scoreStr, options: { bold: true } as any },
        { text: rec, options: {} as any }
      ]);
    });
    
    slide2.addTable(tableRows, {
      x: 0.6, y: 1.1, w: 12.0, h: 4.8,
      fontFace: 'Segoe UI', fontSize: 11,
      border: { type: 'solid', color: 'CBD5E1', pt: 1 },
      align: 'left', valign: 'middle',
      rowH: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
    });

    // Slide 3: Skills Alignment Map
    let slide3 = pptx.addSlide();
    slide3.background = { fill: 'F1F5F9' };
    
    slide3.addText('Pipeline Skills Analysis', {
      x: 0.6, y: 0.4, w: 10.0, h: 0.5,
      fontFace: 'Segoe UI', fontSize: 24, bold: true, color: '0F766E'
    });
    
    // Left: required
    slide3.addText('REQUIRED CRITICAL SKILLS', {
      x: 0.6, y: 1.2, w: 5.5, h: 0.4,
      fontFace: 'Segoe UI', fontSize: 12, bold: true, color: '475569'
    });
    
    slide3.addText(jobSkills.map(s => `• ${s}`).join('\n') || '• Skills as specified in job profile', {
      x: 0.6, y: 1.7, w: 5.5, h: 4.2,
      fontFace: 'Segoe UI', fontSize: 13, color: '334155',
      align: 'left', valign: 'top', lineSpacing: 22
    });
    
    // Right: recommendations
    slide3.addText('TAILORED SOURCING SUGGESTIONS', {
      x: 7.2, y: 1.2, w: 5.5, h: 0.4,
      fontFace: 'Segoe UI', fontSize: 12, bold: true, color: '475569'
    });
    
    const recs = `• Candidate pipeline exhibits strong technical competencies.\n• Sourcing gap identified in secondary methodologies; consider addressing in screening calls.\n• Focus upcoming hiring loops on top 3 ranked prospects.`;
    slide3.addText(recs, {
      x: 7.2, y: 1.7, w: 5.5, h: 4.2,
      fontFace: 'Segoe UI', fontSize: 13, color: '334155',
      align: 'left', valign: 'top', lineSpacing: 24
    });

    const buffer = await pptx.write({ outputType: 'arraybuffer' }) as ArrayBuffer;
    return Buffer.from(buffer);
  }
}

export const presentationService = new PresentationService();
export default presentationService;
