#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1}

# Check branch name (skip if no commits yet)
if git rev-parse --verify HEAD >/dev/null 2>&1; then
  branch=$(git rev-parse --abbrev-ref HEAD)
  if [[ ! $branch =~ ^(main|master|feature/|bugfix/|hotfix/) ]]; then
    echo "Branch name must be 'main', 'master', or start with 'feature/', 'bugfix/', or 'hotfix/'"
    exit 1
  fi
fi