#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1}

# Check branch name
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ ! $branch =~ ^(main|master|feature|bugfix|hotfix)/ ]]; then
  echo "Branch name must start with main/, master/, feature/, bugfix/, or hotfix/"
  exit 1
fi